### ISSUE TITLE
Navigation Active State Not Updating

### ISSUE THREAD

**Issue by BraedenKilburn** [wpinfusion/AstroPie#1]
**Expected Behavior:**
- When navigating between pages, the header should highlight the current route
- Active navigation items should have the `menu-item-active` class applied
- Active items should be displayed in the brand green color

**Current Behavior:**
- Active state works correctly in local development
- In production, the navigation items do not update to reflect the current route
- The `menu-item-active` class is not being applied when changing pages

**Example:**
When navigating to the "Menu" page:
- Local: The "Menu" link in the header is highlighted green
- Production: The "Menu" link remains unstyled

**Comment by wpinfusion** [comment]
Thanks for reporting this. I believe this is something that webhosts like Netlify cause. The reason it's not working is that they append the path with a `/` so navigating to `/menu` becomes `/menu/` which doesn't match Astro's pathname.

One solution is to use trailing slashes in your project as well, so the pathname matches that of Netlify (or whichever host you're using).

I would also encourage you to add your domain config to Astro, like documented here:
https://docs.astro.build/en/guides/configuring-astro/#add-your-deployment-domain

I updated the theme with this solution and the demo is now reflecting that. Having that said, I'm not a big fan of this solution. I wish it would just work with or without a trailing slash. In the Netlify settings you can disable 'pretty links' but unfortunately that didn't solve it for me.

**Comment by wpinfusion** [comment]
@BraedenKilburn I pushed another update where you don't have to use trailing slashes anymore. It should all work as usual now.
